const data = [
  {
    word: "hero",
    palabra: "heroe",
    image: "https://4pics1-word.com/data/images_big/1434.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1434.jpg",
  },
  {
    word: "peace",
    palabra: "paz",
    image: "https://4pics1-word.com/data/images_big/2104.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/4112022.jpg",
  },
  {
    word: "cold",
    palabra: "frio",
    image: "https://4pics1-word.com/data/images_big/12.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/12.jpg",
  },
  {
    word: "wall",
    palabra: "pared",
    image: "https://4pics1-word.com/data/images_big/100321121.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/24032118.jpg",
  },
  {
    word: "mouse",
    palabra: "negro",
    image: "https://4pics1-word.com/data/images_big/477.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/88.jpg",
  },
  {
    word: "ice",
    palabra: "hielo",
    image: "https://4pics1-word.com/data/images_big/479.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/479.jpg",
  },
  {
    word: "egg",
    palabra: "huevo",
    image: "https://4pics1-word.com/data/images_big/3515.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/24031627.jpg",
  },
  {
    word: "gas",
    palabra: "gas",
    image: "https://4pics1-word.com/data/images_big/40417028.jpg",
    imagen: "https://4pics1-word.com/data/images_big/40417028.jpg",
  },
  {
    word: "danger",
    palabra: "alarma",
    image: "https://4pics1-word.com/data/images_big/4539.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/93.jpg",
  },
  {
    word: "ball",
    palabra: "pelota",
    image: "https://4pics1-word.com/data/images_big/48.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/48.jpg",
  },
  {
    word: "jump",
    palabra: "saltar",
    image: "https://4pics1-word.com/data/images_big/171.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/171.jpg",
  },
  {
    word: "war",
    palabra: "guerra",
    image: "https://4pics1-word.com/data/images_big/5722.jpg",
    imagen: "https://4pics1-word.com/data/images_big/5722.jpg",
  },
  {
    word: "wine",
    palabra: "vino",
    image: "https://4pics1-word.com/data/images_big/1449.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1449.jpg",
  },
  {
    word: "bat",
    palabra: "dormir",
    image: "https://4pics1-word.com/data/images_big/122.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/447.jpg",
  },
  {
    word: "sky",
    palabra: "arena",
    image: "https://4pics1-word.com/data/images_big/2125.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/460.jpg",
  },
  {
    word: "kiss",
    palabra: "beso",
    image: "https://4pics1-word.com/data/images_big/1405.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1405.jpg",
  },
  {
    word: "cat",
    palabra: "gato",
    image: "https://4pics1-word.com/data/images_big/4666.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/609.jpg",
  },
  {
    word: "music",
    palabra: "musica",
    image: "https://4pics1-word.com/data/images_big/400.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/400.jpg",
  },
  {
    word: "snow",
    palabra: "nieve",
    image: "https://4pics1-word.com/data/images_big/450.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/450.jpg",
  },
  {
    word: "baby",
    palabra: "bebe",
    image: "https://4pics1-word.com/data/images_big/2450.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/2450.jpg",
  },
  {
    word: "color",
    palabra: "loro",
    image: "https://4pics1-word.com/data/images_big/1730.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/120116087.jpg",
  },
  {
    word: "gold",
    palabra: "oro",
    image: "https://4pics1-word.com/data/images_big/702206.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/702206.jpg",
  },
  {
    word: "fruit",
    palabra: "fruta",
    image: "https://4pics1-word.com/data/images_big/1454.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1454.jpg",
  },
  {
    word: "diving",
    palabra: "buceo",
    image: "https://4pics1-word.com/data/images_big/1400.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1400.jpg",
  },
  {
    word: "gift",
    palabra: "regalo",
    image: "https://4pics1-word.com/data/images_big/1420.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1420.jpg",
  },
  {
    word: "skin",
    palabra: "piel",
    image: "https://4pics1-word.com/data/images_big/1418.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1418.jpg",
  },
  {
    word: "moon",
    palabra: "luna",
    image: "https://4pics1-word.com/data/images_big/5910.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/26082124.jpg",
  },
  {
    word: "animal",
    palabra: "animal",
    image: "https://4pics1-word.com/data/images_big/1402.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1402.jpg",
  },

  {
    word: "snail",
    palabra: "espada",
    image: "https://4pics1-word.com/data/images_big/2569.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/30112157.jpg",
  },
  {
    word: "igloo",
    palabra: "iglu",
    image: "https://4pics1-word.com/data/images_big/7161.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/7161.jpg",
  },
  {
    word: "peach",
    palabra: "mate",
    image: "https://4pics1-word.com/data/images_big/6665.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/24041702.jpg",
  },
  {
    word: "lemur",
    palabra: "lemur",
    image: "https://4pics1-word.com/data/images_big/70616161.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/70616161.jpg",
  },
  {
    word: "draw",
    palabra: "pesado",
    image: "https://4pics1-word.com/data/images_big/483.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/173.jpg",
  },
  {
    word: "comet",
    palabra: "cometa",
    image: "https://4pics1-word.com/data/images_big/291116119.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/625.jpg",
  },
  {
    word: "rose",
    palabra: "rosa",
    image: "https://4pics1-word.com/data/images_big/24082037.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1433.jpg",
  },
  {
    word: "bird",
    palabra: "oso",
    image: "https://4pics1-word.com/data/images_big/2098.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/220815120.jpg",
  },
  {
    word: "dog",
    palabra: "perro",
    image: "https://4pics1-word.com/data/images_big/4672.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/21042172.jpg",
  },
  {
    word: "box",
    palabra: "boxeo",
    image: "https://4pics1-word.com/data/images_big/435.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/17004.jpg",
  },
  {
    word: "hot",
    palabra: "sol",
    image: "https://4pics1-word.com/data/images_big/16.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/618.jpg",
  },
  {
    word: "crown",
    palabra: "corona",
    image: "https://4pics1-word.com/data/images_big/464.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/464.jpg",
  },
  {
    word: "house",
    palabra: "casa",
    image: "https://4pics1-word.com/data/images_big/454.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/454.jpg",
  },
  {
    word: "shoe",
    palabra: "cola",
    image: "https://4pics1-word.com/data/images_big/2106.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/606.jpg",
  },
  {
    word: "goal",
    palabra: "gol",
    image: "https://4pics1-word.com/data/images_big/250719585.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/24111996.jpg",
  },
  {
    word: "honey",
    palabra: "miel",
    image: "https://4pics1-word.com/data/images_big/7212.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/14012161.jpg",
  },
  {
    word: "ink",
    palabra: "tinta",
    image: "https://4pics1-word.com/data/images_big/478.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/478.jpg",
  },
  {
    word: "smile",
    palabra: "risa",
    image: "https://4pics1-word.com/data/images_big/612111616.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/7014.jpg",
  },
  {
    word: "beach",
    palabra: "playa",
    image: "https://4pics1-word.com/data/images_big/28031805.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/28031805.jpg",
  },
  {
    word: "web",
    palabra: "aguja",
    image: "https://4pics1-word.com/data/images_big/6894.jpg",
    imagen: "https://4pics1-word.com/data/images_big/241119264.jpg",
  },
  {
    word: "dark",
    palabra: "llama",
    image: "https://4pics1-word.com/data/images_big/31821625.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/635.jpg",
  },
  {
    word: "car",
    palabra: "sapo",
    image: "https://4pics1-word.com/data/images_big/453.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/20102157.jpg",
  },
  {
    word: "wave",
    palabra: "agua",
    image: "https://4pics1-word.com/data/images_big/143.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/166.jpg",
  },
  {
    word: "dart",
    palabra: "dardo",
    image: "https://4pics1-word.com/data/images_big/21126.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/21126.jpg",
  },
  {
    word: "mother",
    palabra: "madre",
    image: "https://4pics1-word.com/data/images_big/1410.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1410.jpg",
  },
  {
    word: "flag",
    palabra: "ovni",
    image: "https://4pics1-word.com/data/images_big/3543.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/7214.jpg",
  },
  {
    word: "bee",
    palabra: "abeja",
    image: "https://4pics1-word.com/data/images_big/4664.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1312217.jpg",
  },
  {
    word: "canoe",
    palabra: "canoa",
    image: "https://4pics1-word.com/data/images_big/21102146.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/21102146.jpg",
  },
  {
    word: "tiger",
    palabra: "tigre",
    image: "https://4pics1-word.com/data/images_big/4678.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/212191.jpg",
  },
  {
    word: "apple",
    palabra: "puente",
    image: "https://4pics1-word.com/data/images_big/4651.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/1502.jpg",
  },
  {
    word: "salad",
    palabra: "volar",
    image: "https://4pics1-word.com/data/images_big/12347.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/24051953.jpg",
  },
  {
    word: "tango",
    palabra: "tango",
    image: "https://4pics1-word.com/data/images_big/7182.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/7182.jpg",
  },

  {
    word: "dad",
    palabra: "papa",
    image: "https://4pics1-word.com/data/images_big/5703.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/3706.jpg",
  },
  {
    word: "circus",
    palabra: "circo",
    image: "https://4pics1-word.com/data/images_big/2597.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/2597.jpg",
  },
  {
    word: "shout",
    palabra: "jaula",
    image: "https://4pics1-word.com/data/images_big/11145.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/240519102.jpg",
  },
  {
    word: "blind",
    palabra: "marte",
    image: "https://4pics1-word.com/data/images_big/4225.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/26082136.jpg",
  },
  {
    word: "money",
    palabra: "dinero",
    image: "https://4pics1-word.com/data/images_big/7191.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/7191.jpg",
  },
  {
    word: "horse",
    palabra: "lluvia",
    image: "https://4pics1-word.com/data/images_big/2417.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/7042.jpg",
  },
  {
    word: "spray",
    palabra: "azucar",
    image: "https://4pics1-word.com/data/images_big/507.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/12130.jpg",
  },
  {
    word: "brain",
    palabra: "banco",
    image: "https://4pics1-word.com/data/images_big/1406.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/610.jpg",
  },
  {
    word: "wheel",
    palabra: "rueda",
    image: "https://4pics1-word.com/data/images_big/2117.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/21102127.jpg",
  },
  {
    word: "air",
    palabra: "aire",
    image: "https://4pics1-word.com/data/images_big/5700.jpg",
    imagen: "https://4fotos1-palabra.com/data/images_big/16022136.jpg",
  },
];
